---
apiVersion: v1
kind: Namespace
metadata:
  name: otpx
---
# Source: mysql-innodbcluster/templates/service_account_cluster.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-cluster-sa
  namespace: otpx
---
# Source: mysql-innodbcluster/templates/cluster_secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-cluster-secret
  namespace: otpx
stringData:
  rootUser: "otpx"
  rootHost: "%"
  rootPassword: "otpx"
---
# Source: mysql-innodbcluster/templates/deployment_cluster.yaml
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: otpx
spec:
  instances: 3
  tlsUseSelfSigned: true
  router:
    instances: 1
  secretName: mysql-cluster-secret
  imagePullPolicy : IfNotPresent
  baseServerId: 1000
  version: 8.3.0
  serviceAccountName: mysql-cluster-sa

  mycnf: |
    [mysqld]
    max_connections=162

  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1G

  podSpec:
    containers:
    - name: mysql
      resources:
        limits:
          memory: "2G"
          cpu: "2"
        requests:
          memory: "0Mi"
          cpu: "0"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: "true"
        effect: "PreferNoSchedule"

  #logs:
  #  error:
  #    enabled: true
  #    collect: false
  #  general:
  #    enabled: false
  #    collect: false
  #  slowQuery:
  #    enabled: false
  #    longQueryTime: 2.5
  #  collector:
  #    image: "192.168.20.198:5000/fluentd-es:v1.16"
  #    fluentd:
  #      forwarding:
  #        enabled: false
  #        forwarderSpec:
  #          podSpec:
  #            terminationGracePeriod: 42
  #          podAnnotations:
  #            forwarderAnnotation1: forwarderAnnotation1Value
  #          podLabels:
  #            forwarderLabel1: forwarderLabel1Value
  #      generalLog:
  #        tag: "genLogTag"
  ##        options:
  #      errorLog:
  #        tag: "errLogTag"
  ##        options:
  ##      slowLog:
  #        tag: "slowLogTag"
  ##        options:
  #     recordAugmentation:
  #        enabled: false
  #        labels:
  #        - fieldName: "pod_name"
  #          labelName: "statefulset.kubernetes.io/pod-name"
  #        annotations:
  #        - fieldName: "membership-info"
  #          labelName: "mysql.oracle.com/membership-info"
  #        staticFields:
  #        - fieldName: "static_field_1"
  #          fieldValue: "static_field_1_value"
  #        resourceFields:
  #        - fieldName: "pod_ip"
  #          fieldPath: "status.podIP"
  #        - fieldName: "host_ip"
  #          fieldPath: "status.hostIP"
  #      additionalFilterConfiguration: |
  #        filterConfigValueLine1
  #        filterConfigValueLine1
  #      sink:
  ##       rawConfig:

  #keyring:
  #  file:
  #    fileName:
  #    readOnly:
  #    storage:
  #  encryptedFile:
  #    fileName:
  #    readOnly:
  #    storage:
  #    password:
  #  oci:
  #    user: "ocid1.user.oc1..."
  #    keySecret: "oci-credentials"
  #    keyFingerprint: ""
  #    tenancy: "ocid1.tenancy.oc1..."
  #    compartment: "ocid1.compartment.oc1..."
  #    virtualVault: "ocid1.vault.oc1.."
  #    masterKey: "ocid1.key.oc1..."
  #    caCertificate: ""
  #    endpoints:
  #      encryption: "<identifier>-crypto.kms.<region>.oraclecloud.com"
  #      management: "<identifier>-management.kms.<region>.oraclecloud.com"
  #      vaults: "vaults.<region>.oci.oraclecloud.com"
  #      secrets: "secrets.vaults.<region>.oci.oraclecloud.com"

  #podAnnotations:
  #podLabels:

  #serverConfig:
  #  mycnf: |
  #    [mysqld]
  #    core_file
  #    local_infile=off

  #datadirVolumeClaimTemplate:
  #  accessModes:
  #  resources:
  #    requests:
  #      storage:

  #initDB:
  #  dump:
  #    name:
  #    path:
  #    options:
  #      includeSchemas:
  #    ociObjectStorage:
  #      prefix:
  #      bucketName:
  #      credentials:
  #    s3:
  #      prefix:
  #      config:
  #      bucketName:
  #      profile:
  #      endpoint
  #    azure:
  #      prefix:
  #      config:
  #      containerName:
  #    persistentVolumeClaim:
  #  clone:
  #    donorUrl:
  #    rootUser:
  #    credentials:


  #backupProfiles:
  #- name: dump-instance-profile-pvc
  #  dumpInstance:
  #    dumpOptions:
  #      excludeSchemas: ["excludeme"]
  #    storage:
  #      persistentVolumeClaim:
  #        claimName: backup-volume-claim-1
  #- name: dump-instance-profile-oci
  #  dumpInstance:
  #    dumpOptions:
  #      excludeSchemas: ["excludeme"]
  #    storage:
  #      ociObjectStorage:
  #        prefix : /
  #        bucketName: idbcluster_backup
  #        credentials: oci-credentials
  #
  #- name: snapshot-profile-oci
  #  snapshot:
  #    storage:
  #      ociObjectStorage:
  #        prefix : /
  #        bucketName: idbcluster_backup
  #        credentials: oci-credentials
  #      s3:
  #        prefix:
  #        config:
  #        bucketName:
  #        profile:
  #        endpoint
  #      azure:
  #        prefix:
  #        config:
  #        containerName:

  #backupSchedules:
  #- name: schedule-ref
  #  schedule: "*/1 * * * *"
  #  timeZone: "Europe/Amsterdam"
  #  deleteBackupData: false
  #  backupProfileName: dump-instance-profile-oci
  #  enabled: true
  #- name: schedule-inline
  #  schedule: "*/1 * * * *"
  #  timeZone: "Europe/Amsterdam"
  #  deleteBackupData: false
  #  enabled: true
  #  backupProfile:
  #    dumpInstance:
  #      dumpOptions:
  #        excludeSchemas: ["excludeme"]
  #      storage:
  #        ociObjectStorage:
  #          prefix : /
  #          bucketName: idbcluster_backup
  #          credentials: oci-credentials
